# Generated by Django 4.1.3 on 2022-12-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
